apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-exercises
  name: pingpong-dep
spec:
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: eu.gcr.io/strax-dwk/pingpong@sha256:38299538376d08238f99c18a2ba69a5829fca0431269de0d1970ff46fbd6f14f
          envFrom:
            - configMapRef:
                name: pingpong-config
            - secretRef:
                name: pingpong-secret
          readinessProbe:
            httpGet:
              port: 80
              path: /health
            initialDelaySeconds: 30